services:
  postgres:
    image: postgres:17
    container_name: banking-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.4
    container_name: banking-keycloak
    command:
      - start-dev
      - --import-realm
      - --hostname=http://localhost:8081
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
   # ports:
    #  - "8081:8080"

  backend:
    build:
      context: ./backend
    container_name: banking-backend
    environment:
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${OAUTH2_ISSUER_URI}

      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/banking/protocol/openid-connect/certs

    expose:
      - "8080"

    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started

    restart: unless-stopped

  frontend:
    image: node:22-alpine
    container_name: banking-frontend
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --hostname 0.0.0.0 --port 3000"
    volumes:
      - ./frontend:/app
    expose:
      - "3000"
    depends_on:
      - backend
      - keycloak

  nginx:
    image: nginx:alpine
    container_name: banking-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - keycloak
    restart: unless-stopped

volumes:
  postgres_data: